package:
  name: m4
  version: 1.4.18

source:
  fn: m4-1.4.18.tar.gz
  url: http://ftp.gnu.org/pub/gnu/m4/m4-1.4.18.tar.gz

requirements:
  build:

  run:

about:
  home: https://www.gnu.org/software/m4/
  license:  GPLv3
