package:
  name: mpltools
  version: "0.2.0"

source:
  fn: mpltools-0.2.0.tar.gz
  url: https://pypi.python.org/packages/source/m/mpltools/mpltools-0.2.0.tar.gz
  md5: 97e222b4649492554e008a077a4183fb
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mpltools = mpltools:main
    #
    # Would create an entry point called mpltools that calls mpltools.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - matplotlib >=1.0
    - configobj >=4.4.0
    - future >=0.12.4

  run:
    - python
    - matplotlib >=1.0
    - configobj >=4.4.0
    - future >=0.12.4

test:
  # Python imports
  imports:
    - mpltools
    - mpltools.annotation
    - mpltools.io
    - mpltools.special
    - mpltools.sphinx
    - mpltools.style
    - mpltools.widgets

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://tonysyu.github.com/mpltools/
  license: Modified BSD
  summary: 'Tools for Matplotlib'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
