package:
  name: assertpy
  version: !!str 0.9

source:
  fn: assertpy-0.9.tar.gz
  url: https://pypi.python.org/packages/source/a/assertpy/assertpy-0.9.tar.gz
  md5: f302f4089e38c79e461356dc048f556c 

build:
  noarch_python: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - assertpy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ActivisionGameScience/assertpy
  license: BSD License
  summary: 'Assertion framework for python unit testing with a fluent API'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
