package:
  name: r-project
  version: 3.1.3

source:
  fn: R-3.1.3.tar.gz
  url: http://cran.r-project.org/src/base/R-3/R-3.1.3.tar.gz

requirements:
  build:
    - ncurses
    - readline

  run:
    - ncurses
    - readline

about:
  home: r-project.org
  license:  GPL
