package:
  name: python-dateutil
  version: "2.5.3"

source:
  fn: python-dateutil-2.5.3.tar.gz
  url: https://pypi.python.org/packages/3e/f5/aad82824b369332a676a90a8c0d1e608b17e740bbb6aeeebca726f17b902/python-dateutil-2.5.3.tar.gz
  md5: 05ffc6d2cc85a7fd93bb245807f715ef
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-dateutil = python-dateutil:main
    #
    # Would create an entry point called python-dateutil that calls python-dateutil.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six >=1.5

  run:
    - python
    - six >=1.5

test:
  # Python imports
  imports:
    - dateutil
    - dateutil.tz
    - dateutil.zoneinfo

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://dateutil.readthedocs.org
  license: BSD License
  summary: 'Extensions to the standard Python datetime module'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
