package:
  name: betamax-matchers
  version: "0.2.0"

source:
  fn: betamax-matchers-0.2.0.tar.gz
  url: https://pypi.python.org/packages/source/b/betamax-matchers/betamax-matchers-0.2.0.tar.gz
  md5: b82264fc3628e261353261a654370535
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - betamax-matchers = betamax-matchers:main
    #
    # Would create an entry point called betamax-matchers that calls betamax-matchers.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - betamax >=0.3.2
    - requests-toolbelt >=0.4.0

  run:
    - python
    - betamax >=0.3.2
    - requests-toolbelt >=0.4.0

test:
  # Python imports
  imports:
    - betamax_matchers

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/sigmavirus24/betamax_matchers
  license: yes
  summary: 'A VCR imitation for python-requests'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
