package:
  name: assertpy
  version: !!str 0.11

source:
  fn: assertpy-0.11.tar.gz
  url: https://pypi.python.org/packages/cf/65/866d43185d3aa104e65fe30567d0c93fbe3035b913be4c2eb789d83d3ae5/assertpy-0.11.tar.gz#md5=dda697cd04c7dc2d1f0c3559a2048f4a
  md5: dda697cd04c7dc2d1f0c3559a2048f4a

build:
  noarch_python: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - assertpy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ActivisionGameScience/assertpy
  license: BSD License
  summary: 'Assertion library for python unit testing with a fluent API'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
