package:
  name: pykafka
  version: "2.1.1"

source:
  fn: 2.1.1.tar.gz
  url: https://github.com/Parsely/pykafka/archive/2.1.1.tar.gz
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-snappy = python-snappy:main
    #
    # Would create an entry point called python-snappy that calls python-snappy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - librdkafka
    - tabulate
    - kazoo

  run:
    - python
    - librdkafka
    - tabulate
    - kazoo

test:
  # Python imports
  imports:
    - pykafka

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/Parsely/pykafka
  license: Apache License 2.0
  summary: 'Python library to talk to Kafka topics'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
