package:
  name: bz2file
  version: "0.98"

source:
  fn: bz2file-0.98.tar.gz
  url: https://pypi.python.org/packages/source/b/bz2file/bz2file-0.98.tar.gz
  md5: 27d6f711ae0db6cfd1eb37f95621dfb5
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - bz2file = bz2file:main
    #
    # Would create an entry point called bz2file that calls bz2file.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - bz2file

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/nvawda/bz2file
  license: Apache Software License
  summary: 'Read and write bzip2-compressed files.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
