package:
  name: caffe
  version: rc3

source:
  fn: rc3.tar.gz
  url: https://github.com/BVLC/caffe/archive/rc3.tar.gz 
  md5:  

build:
  number: 0

requirements:
  build:
    - cmake
    - boost
    - protobuf
    - glog
    - gflags
    - hdf5
    - leveldb
    - lmdb
    - opencv
    - python
    - numpy

  run:
    - boost
    - protobuf
    - glog
    - gflags
    - hdf5
    - leveldb
    - lmdb
    - opencv
    - python
    - numpy

about:
  home: http://github.org/BVLC/caffe
  license:  BSD 2-clause
