package:
  name: beaker
  version: !!str 1.6.4

source:
  fn: Beaker-1.6.4.tar.gz
  url: https://pypi.python.org/packages/source/B/Beaker/Beaker-1.6.4.tar.gz
  md5: c2e102870ed4c53104dec48ceadf8e9d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - beaker = beaker:main
    #
    # Would create an entry point called beaker that calls beaker.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - beaker
    - beaker.crypto
    - beaker.ext

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://beaker.rtfd.org/
  license:  BSD License
  summary: 'A Session and Caching library with WSGI Middleware'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
