package:
  name: vertica-python
  version: !!str 0.3.0

source:
  fn: vertica-python-0.3.0.tar.gz
  url: https://pypi.python.org/packages/source/v/vertica-python/vertica-python-0.3.0.tar.gz
  md5: 4a9e73f5ab1f4bdab1a846997cd4a397
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - vertica-python = vertica-python:main
    #
    # Would create an entry point called vertica-python that calls vertica-python.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - python-dateutil >=1.5
    - pytz

  run:
    - python
    - python-dateutil >=1.5
    - pytz

test:
  # Python imports
  imports:
    - vertica_python
    - vertica_python.vertica
    - vertica_python.vertica.messages
    - vertica_python.vertica.messages.backend_messages
    - vertica_python.vertica.messages.frontend_messages

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/uber/vertica-python/
  license:  MIT License
  summary: 'A native Python client for the Vertica database.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
