package:
  name: confluent-kafka
  version: "0.11.5"

source:
  fn: v0.11.5.tar.gz
  url: https://github.com/confluentinc/confluent-kafka-python/archive/v0.11.5.tar.gz
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch: python
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - confluent-kafka = confluent-kafka:main
    #
    # Would create an entry point called confluent-kafka that calls confluent-kafka.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - librdkafka
    - avro-python3

  run:
    - python
    - librdkafka 0.11.5
    - requests
    - avro-python3

test:
  # Python imports
  imports:
    - confluent_kafka
    - confluent_kafka.avro
    - confluent_kafka.avro.serializer
    - confluent_kafka.kafkatest

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/confluentinc/confluent-kafka-python
  license: Apache 2.0
  summary: "Confluent's Apache Kafka client for Python"
  license_family: APACHE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
