
package:
    name: ant
    version: 1.9.4
source:
    fn: apache-ant-1.9.4-bin.zip
    url: http://ftp.ps.pl/pub/apache/ant/binaries/apache-ant-1.9.4-bin.zip
    md5: 2cb5143be8d22c9a8562e6cc18f40009 

build:
    number: 0

requirements:
    build:
        - jdk
    run:
        - jdk

test:
    commands:
        - ant -version

about:
    home: http://ant.apache.org/
    license: Apache License v2.0

