package:
  name: maxminddb
  version: "1.2.0"

source:
  fn: maxminddb-1.2.0.tar.gz
  url: https://pypi.python.org/packages/source/m/maxminddb/maxminddb-1.2.0.tar.gz
  md5: 2c5b4b602568b578ec1f7ef5cd89b681
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - maxminddb = maxminddb:main
    #
    # Would create an entry point called maxminddb that calls maxminddb.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - libmaxminddb

  run:
    - python
    - libmaxminddb

test:
  # Python imports
  imports:
    - maxminddb

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.maxmind.com/
  license: Apache Software License
  summary: 'Python extension for reading the MaxMind DB format'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
