#!/bin/bash

C_INCLUDE_PATH=$PREFIX/include make prefix=$PREFIX CURLDIR=$PREFIX EXPATDIR=$PREFIX NO_PERL=1 NO_INSTALL_HARDLINKS=YesPlease all
C_INCLUDE_PATH=$PREFIX/include make prefix=$PREFIX CURLDIR=$PREFIX EXPATDIR=$PREFIX NO_PERL=1 NO_INSTALL_HARDLINKS=YesPlease install
