package:
  name: autopep8
  version: "1.1.1"

source:
  fn: autopep8-1.1.1.tar.gz
  url: https://pypi.python.org/packages/source/a/autopep8/autopep8-1.1.1.tar.gz
  md5: e52f1a9a3df04d7706451a80345cf3ec
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - autopep8 = autopep8:main
    #
    # Would create an entry point called autopep8 that calls autopep8.main()

    - autopep8 = autopep8:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pep8 >=1.5.7

  run:
    - python
    - pep8 >=1.5.7

test:
  # Python imports
  imports:
    - autopep8

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - autopep8 --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/hhatto/autopep8
  license: MIT License
  summary: 'A tool that automatically formats Python code to conform to the PEP 8 style guide'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
