package:
  name: pytz
  version: "2016.4"

source:
  fn: pytz-2016.4.tar.bz2
  url: https://pypi.python.org/packages/f4/7d/7c0c85e9c64a75dde11bc9d3e1adc4e09a42ce7cdb873baffa1598118709/pytz-2016.4.tar.bz2
  md5: e56283d61935963157aebc5135206a47
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pytz = pytz:main
    #
    # Would create an entry point called pytz that calls pytz.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pytz

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pythonhosted.org/pytz
  license: MIT License
  summary: 'World timezone definitions, modern and historical'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
