package:
  name: snappy
  version: 1.1.3

source:
  fn: snappy-1.1.3.tar.gz
  url: https://github.com/google/snappy/releases/download/1.1.3/snappy-1.1.3.tar.gz
  md5: 7358c82f133dc77798e4c2062a749b73

build:
  number: 0

requirements:
  build:
    - automake
    - autoconf
    - libtool

  run:

about:
  home: https://github.com/google/snappy
  license:  BSD
