package:
  name: bottle
  version: !!str 0.12.7

source:
  fn: bottle-0.12.7.tar.gz
  url: https://pypi.python.org/packages/source/b/bottle/bottle-0.12.7.tar.gz
  md5: ed0b83c9dbbdbde784e7c652d61c59f4
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - bottle = bottle:main
    #
    # Would create an entry point called bottle that calls bottle.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - bottle

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bottlepy.org/
  license:  MIT License
  summary: 'Fast and simple WSGI-framework for small web-applications.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
