package:
  name: betamax
  version: "0.5.1"

source:
  fn: betamax-0.5.1.tar.gz
  url: https://pypi.python.org/packages/source/b/betamax/betamax-0.5.1.tar.gz
  md5: 349e69e1a9da664a8ab8c0f545e2e38f
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - betamax = betamax:main
    #
    # Would create an entry point called betamax that calls betamax.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=2.0

  run:
    - python
    - setuptools
    - requests >=2.0

test:
  # Python imports
  imports:
    - betamax
    - betamax.cassette
    - betamax.fixtures
    - betamax.matchers
    - betamax.serializers

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/sigmavirus24/betamax
  license: yes
  summary: 'A VCR imitation for python-requests'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
