package:
  name: pyjq
  version: "2.1.0"

source:
  fn: v2.1.0.tar.gz
  url: https://github.com/doloopwhile/pyjq/archive/v2.1.0.tar.gz
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-snappy = python-snappy:main
    #
    # Would create an entry point called python-snappy that calls python-snappy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - make
    - libtool
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - pyjq

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/doloopwhile/pyjq 
  license: Apache License 2.0

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
