package:
  name: pyquery
  version: "1.2.11"

source:
  fn: pyquery-1.2.11.tar.gz
  url: https://pypi.python.org/packages/source/p/pyquery/pyquery-1.2.11.tar.gz
  md5: 394ff9a4b2a811581b3f8353bd21ed26
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyquery = pyquery:main
    #
    # Would create an entry point called pyquery that calls pyquery.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - lxml >=2.1
    - cssselect >0.7.9

  run:
    - python
    - setuptools
    - lxml >=2.1
    - cssselect >0.7.9

test:
  # Python imports
  imports:
    - pyquery

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/gawel/pyquery
  license: BSD
  summary: 'A jquery-like library for python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
