package:
  name: ansible
  version: !!str 1.7.2

source:
  fn: ansible-1.7.2.tar.gz
  url: https://pypi.python.org/packages/source/a/ansible/ansible-1.7.2.tar.gz
  md5: 6c9112a2e7d7d1394c97e57290fc13be
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ansible = ansible:main
    #
    # Would create an entry point called ansible that calls ansible.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - paramiko
    - jinja2
    - pyyaml
    - setuptools
    - pycrypto >=2.6

  run:
    - python
    - paramiko
    - jinja2
    - pyyaml
    - setuptools
    - pycrypto >=2.6

test:
  # Python imports
  imports:
    - ansible
    - ansible.callback_plugins
    - ansible.inventory
    - ansible.inventory.vars_plugins
    - ansible.module_utils
    - ansible.playbook
    - ansible.runner
    - ansible.runner.action_plugins
    - ansible.runner.connection_plugins
    - ansible.runner.filter_plugins
    - ansible.runner.lookup_plugins
    - ansible.runner.shell_plugins
    - ansible.utils
    - ansible.utils.module_docs_fragments

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://ansible.com/
  license: GPLv3
  summary: 'Radically simple IT automation'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
