package:
  name: librdkafka
  version: 0.11.5

source:
  fn: v0.11.5.tar.gz
  url: https://github.com/edenhill/librdkafka/archive/v0.11.5.tar.gz

build:
  number: 0

requirements:
  build:

  run:

about:
  home: https://github.com/edenhill/librdkafka
  license:  BSD
