package:
  name: pygal
  version: !!str 1.5.1

source:
  fn: pygal-1.5.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pygal/pygal-1.5.1.tar.gz
  md5: dcdd03fa76e8db3019beb15d1173e71b
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pygal = pygal:main
    #
    # Would create an entry point called pygal that calls pygal.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pygal
    - pygal.graph
    - pygal.test

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pygal.org/
  license:  GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'A python svg graph plotting library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
