package:
  name: nosexcover
  version: "1.0.10"

source:
  fn: nosexcover-1.0.10.tar.gz
  url: https://pypi.python.org/packages/source/n/nosexcover/nosexcover-1.0.10.tar.gz
  md5: 12bf494a801b376debeb6a167c247391
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - nosexcover = nosexcover:main
    #
    # Would create an entry point called nosexcover that calls nosexcover.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - nose
    - coverage >=3.4

  run:
    - python
    - setuptools
    - nose
    - coverage >=3.4

test:
  # Python imports
  imports:
    - nosexcover

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/cmheisel/nose-xcover/
  license: BSD License
  summary: 'Extends nose.plugins.cover to add Cobertura-style XML reports'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
