package:
  name: librdkafka
  version: 0.9.1

source:
  fn: 0.9.1.tar.gz
  url: https://github.com/edenhill/librdkafka/archive/0.9.1.tar.gz

build:
  number: 0

requirements:
  build:

  run:

about:
  home: https://github.com/edenhill/librdkafka
  license:  BSD
