package:
  name: brewer2mpl
  version: "1.4.1"

source:
  fn: brewer2mpl-1.4.1.tar.gz
  url: https://pypi.python.org/packages/source/b/brewer2mpl/brewer2mpl-1.4.1.tar.gz
  md5: f8cd1fbb9f5d836a3a095b1ca9d58fc2
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - brewer2mpl = brewer2mpl:main
    #
    # Would create an entry point called brewer2mpl that calls brewer2mpl.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - brewer2mpl
    - brewer2mpl.wesanderson

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jiffyclub/brewer2mpl/wiki
  license: MIT License
  summary: 'Connect colorbrewer2.org color maps to Python and matplotlib'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
