package:
  name: pydruid
  version: !!str 0.2.0

source:
  fn: pydruid-0.2.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pydruid/pydruid-0.2.0.tar.gz
  md5: 878c8a2e1108e80d144d8f9812653d8d
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pydruid = pydruid:main
    #
    # Would create an entry point called pydruid that calls pydruid.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - simplejson >=3.3.0

  run:
    - python
    - simplejson >=3.3.0

test:
  # Python imports
  imports:
    - pydruid
    - pydruid.utils

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/pydruid/
  license: LICENSE
  summary: 'A Python connector for Druid.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
