package:
  name: cherrypy
  version: "7.0.0"

source:
  fn: CherryPy-7.0.0.tar.gz
  url: https://pypi.python.org/packages/50/c6/6c3d7a3221b0f098f8684037736e5604ea1586a3ba450c4a52b48f5fc2b4/CherryPy-7.0.0.tar.gz#md5=941568e6818aa565f7a4e19b65ccd582
  md5: 941568e6818aa565f7a4e19b65ccd582 
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cherrypy = cherrypy:main
    #
    # Would create an entry point called cherrypy that calls cherrypy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - cherrypy
    - cherrypy.lib
    - cherrypy.process
    - cherrypy.scaffold
    - cherrypy.test
    - cherrypy.tutorial
    - cherrypy.wsgiserver

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.cherrypy.org
  license: BSD License
  summary: 'Object-Oriented HTTP framework'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
