package:
  name: python-gflags
  version: "3.0.5"

source:
  fn: python-gflags-3.0.5.tar.gz
  url: https://pypi.python.org/packages/1f/01/3ca6527f51b7ff26abb635d4e7e2fa8413c7cf191564cc2c1e535f50dec7/python-gflags-3.0.5.tar.gz
  md5: 0e3a06cb99b9883bf6abacc489f31297
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-gflags = python-gflags:main
    #
    # Would create an entry point called python-gflags that calls python-gflags.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
      #  - six
      #  - gflags
      #  - gflags.third_party
      #  - gflags.third_party.pep257

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/google/python-gflags
  license: BSD
  summary: 'Google Commandline Flags Module'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
