package:
  name: urllib3
  version: "1.14"

source:
  fn: urllib3-1.14.tar.gz
  url: https://pypi.python.org/packages/source/u/urllib3/urllib3-1.14.tar.gz
  md5: 5e1407428ac33b521c71a7ac273b3847
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - urllib3 = urllib3:main
    #
    # Would create an entry point called urllib3 that calls urllib3.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.packages
    - urllib3.packages.ssl_match_hostname
    - urllib3.util

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - mock
    - nose
    - tornado
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://urllib3.readthedocs.org/
  license: MIT License
  summary: 'HTTP library with thread-safe connection pooling, file post, and more.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
