package:
  name: py-radix
  version: "0.9.3"

source:
  fn: py-radix-0.9.3.tar.gz
  url: https://pypi.python.org/packages/source/p/py-radix/py-radix-0.9.3.tar.gz
  md5: 2b5456ae8ab03c7461eb364076afa2cb
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - py-radix = py-radix:main
    #
    # Would create an entry point called py-radix that calls py-radix.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - radix

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/mjschultz/py-radix
  license: BSD License
  summary: 'Radix tree implementation'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
