package:
  name: datadog
  version: "0.16.0"

source:
  fn: datadog-0.16.0.tar.gz
  url: https://pypi.python.org/packages/1d/9b/060879c4b7364b82461260760cead12fe6cbaa078ff335467fbabaa29d2c/datadog-0.16.0.tar.gz#md5=6566b17a7a8ad85a62f7c184df3c1585
  md5: 6566b17a7a8ad85a62f7c184df3c1585 
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - env-excavator = env-excavator:main
    #
    # Would create an entry point called env-excavator that calls env-excavator.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - decorator
    - requests
    - simplejson

  run:
    - python
    - decorator
    - requests
    - simplejson

test:
  # Python imports
  imports:
    - datadog

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/simpleenergy/env-excavator
  license: BSD License
  summary: 'Tools for exconverting environment variables to native python objects'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
