package:
  name: httplib2
  version: !!str 0.9

source:
  fn: httplib2-0.9.zip
  url: https://pypi.python.org/packages/source/h/httplib2/httplib2-0.9.zip
  md5: bdad6a844e0cb890b681fe7c811cfea5
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - httplib2 = httplib2:main
    #
    # Would create an entry point called httplib2 that calls httplib2.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - httplib2

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jcgregorio/httplib2
  license:  MIT License
  summary: 'A comprehensive HTTP client library.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
