package:
  name: protobuf
  version: 3.1.0

source:
  git_url: https://github.com/google/protobuf
  git_tag: v3.1.0

requirements:
  build:
#    - m4  Need to just apt-get install m4 because some dumbass hardcoded /usr/bin/m4
    - autoconf
    - automake
    - libtool
    - pkg-config
    - python
    - cython
    - setuptools
    - google-apputils

  run:

    - python
    - cython
    - google-apputils

about:
  home: https://developers.google.com/protocol-buffers/
  license:  BSD 3-clause
