package:
  name: python-slugify
  version: "1.1.4"

source:
  fn: python-slugify-1.1.4.tar.gz
  url: https://pypi.python.org/packages/source/p/python-slugify/python-slugify-1.1.4.tar.gz
  md5: 8ea8d2cd3433aef40dab408bf0b49a76
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - python-slugify = python-slugify:main
    #
    # Would create an entry point called python-slugify that calls python-slugify.main()

    - slugify=slugify.slugify:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - unidecode >=0.04.16

  run:
    - python
    - unidecode >=0.04.16

test:
  # Python imports
  imports:
    - slugify

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

      #- slugify --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/un33k/python-slugify
  license: BSD License
  summary: 'A Python Slugify application that handles Unicode'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
