package:
  name: pycapnp
  version: "0.5.7"

source:
  fn: pycapnp-0.5.7.tar.gz
  url: https://pypi.python.org/packages/source/p/pycapnp/pycapnp-0.5.7.tar.gz
  md5: d47396d6724593afcbb728b87ac6de07
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pycapnp = pycapnp:main
    #
    # Would create an entry point called pycapnp that calls pycapnp.main()

    - capnpc-cython = capnp._gen:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - cython
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - capnp

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

      #    - capnpc-cython --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/jparyani/pycapnp
  license: BSD License
  summary: "A cython wrapping of the C++ Cap'n Proto library"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
