package:
  name: memory_profiler
  version: !!str 0.31

source:
  fn: memory_profiler-0.31.tar.gz
  url: https://pypi.python.org/packages/source/m/memory_profiler/memory_profiler-0.31.tar.gz
  md5: ab10ff2485a4258cd39237a0bf4b0295
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - memory_profiler = memory_profiler:main
    #
    # Would create an entry point called memory_profiler that calls memory_profiler.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - memory_profiler

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pypi.python.org/pypi/memory_profiler
  license: Simplified BSD
  summary: 'A module for monitoring memory usage of a python program'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
