package:
  name: tweepy
  version: "3.5.0"

source:
  fn: tweepy-3.5.0.tar.gz
  url: https://pypi.python.org/packages/source/t/tweepy/tweepy-3.5.0.tar.gz
  md5: b57b6b75825dc7ca89df428504744297
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - tweepy = tweepy:main
    #
    # Would create an entry point called tweepy that calls tweepy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests >=2.4.3
    - requests-oauthlib >=0.4.1
    - six >=1.7.3

  run:
    - python
    - requests >=2.4.3
    - requests-oauthlib >=0.4.1
    - six >=1.7.3

test:
  # Python imports
  imports:
    - examples
    - tweepy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/tweepy/tweepy
  license: MIT License
  summary: 'Twitter library for python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
