package:
  name: assertpy
  version: !!str 0.7

source:
  fn: assertpy-0.7.tar.gz
  url: https://pypi.python.org/packages/source/a/assertpy/assertpy-0.7.tar.gz
  md5: 63ad901b4475462b516cc7cf3e4644a8
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - assertpy = assertpy:main
    #
    # Would create an entry point called assertpy that calls assertpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - assertpy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/ActivisionGameScience/assertpy
  license: BSD License
  summary: 'Assertion framework for python unit testing with a fluent API'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
