package:
  name: ipy_table
  version: !!str 1.12

source:
  fn: ipy_table-v1.12.tgz
  url: https://pypi.python.org/packages/source/i/ipy_table/ipy_table-v1.12.tgz
  md5: 7c5174e1da986d4b5d4c6b7d9bce26c8
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - ipy_table = ipy_table:main
    #
    # Would create an entry point called ipy_table that calls ipy_table.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - ipy_table

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://epmoyer.github.com/ipy_table/
  license:  BSD License
  summary: 'Easily create richly formatted tables in an IPython Notebook'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
