package:
  name: pandasql
  version: "0.7.1"

source:
  fn: pandasql-0.7.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pandasql/pandasql-0.7.1.tar.gz
  md5: 3e7bfc0f0da62d679b339842f3615e23
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pandasql = pandasql:main
    #
    # Would create an entry point called pandasql that calls pandasql.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - pandas
    - sqlalchemy

  run:
    - python
    - numpy
    - pandas
    - sqlalchemy

test:
  # Python imports
  imports:
    - pandasql
    - pandasql.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/yhat/pandasql/
  license: yes
  summary: 'sqldf for pandas'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
