package:
  name: langid
  version: !!str 1.1.4dev

source:
  fn: langid-1.1.4dev.tar.gz
  url: https://pypi.python.org/packages/source/l/langid/langid-1.1.4dev.tar.gz
  md5: 16a7f43e482562dbebabf1c6bbf7cf8d
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - langid = langid:main
    #
    # Would create an entry point called langid that calls langid.main()

    - langid = langid.langid:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy 1.9.2

  run:
    - python
    - numpy 1.9.2

test:
  # Python imports
  imports:
    - langid
    - langid.train

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - langid --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/saffsd/langid.py
  license: BSD
  summary: 'langid.py is a standalone Language Identification (LangID) tool.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
